package main

import (
	"math"
)

// PageID is generated by increasing order of minScore: smaller ID, smaller score
const lastPID = math.MaxInt64

type PageMeta struct {
	impressions int
	minScore    float32
	features    []Feature
	weights     []float32
}
